import {
  DashboardData,
  Employee,
  NotificationItem,
  ReportData,
  Subscription,
} from "./types";

export const dashboardData: DashboardData = {
  totalSubscriptions: 42,
  monthlySpend: 28760,
  currency: "USD",
  expiring: [
    { days: 30, count: 6 },
    { days: 90, count: 13 },
    { days: 180, count: 21 },
    { days: 365, count: 34 },
  ],
  upcomingRenewals: [
    { id: "s1", name: "Notion Enterprise", date: "2026-05-10", cost: 1200, currency: "USD" },
    { id: "s2", name: "Figma Org", date: "2026-05-14", cost: 960, currency: "USD" },
    { id: "s3", name: "Slack Pro", date: "2026-05-18", cost: 1400, currency: "USD" },
    { id: "s4", name: "Google Workspace", date: "2026-05-20", cost: 2300, currency: "USD" },
    { id: "s5", name: "Miro Business", date: "2026-05-25", cost: 780, currency: "USD" },
  ],
  recentChanges: [
    { id: "c1", text: "Подписка Jira обновлена до Premium", at: "2ч назад" },
    { id: "c2", text: "HR отделу назначен Miro", at: "6ч назад" },
    { id: "c3", text: "Добавлен новый отдел Data", at: "1д назад" },
    { id: "c4", text: "Деактивирована подписка Zoom Webinar", at: "2д назад" },
  ],
};

export const subscriptions: Subscription[] = [
  {
    id: "s1",
    name: "Notion Enterprise",
    category: "Продуктивность",
    status: "active",
    department: "Операции",
    cost: 1200,
    currency: "USD",
    billingCycle: "month",
    nextPayment: "2026-05-10",
    users: ["e1", "e2"],
  },
  {
    id: "s2",
    name: "Figma Org",
    category: "Дизайн",
    status: "expiring",
    department: "Продукт",
    cost: 960,
    currency: "USD",
    billingCycle: "month",
    nextPayment: "2026-05-14",
    users: ["e2", "e3"],
  },
  {
    id: "s3",
    name: "Jira Software",
    category: "DevOps",
    status: "inactive",
    department: "Разработка",
    cost: 1800,
    currency: "USD",
    billingCycle: "year",
    nextPayment: "2026-09-01",
    users: ["e1"],
  },
  {
    id: "s4",
    name: "Google Workspace",
    category: "Офис",
    status: "active",
    department: "Операции",
    cost: 2300,
    currency: "USD",
    billingCycle: "month",
    nextPayment: "2026-05-20",
    users: ["e4", "e5", "e6"],
  },
  {
    id: "s5",
    name: "Miro Business",
    category: "Коллаборация",
    status: "active",
    department: "HR",
    cost: 780,
    currency: "USD",
    billingCycle: "month",
    nextPayment: "2026-05-25",
    users: ["e7", "e8"],
  },
  {
    id: "s6",
    name: "GitLab Ultimate",
    category: "DevOps",
    status: "expiring",
    department: "Разработка",
    cost: 4200,
    currency: "USD",
    billingCycle: "year",
    nextPayment: "2026-06-02",
    users: ["e1", "e9"],
  },
  {
    id: "s7",
    name: "HubSpot CRM",
    category: "CRM",
    status: "active",
    department: "Продажи",
    cost: 3500,
    currency: "USD",
    billingCycle: "month",
    nextPayment: "2026-06-06",
    users: ["e10", "e11"],
  },
  {
    id: "s8",
    name: "Intercom",
    category: "Поддержка",
    status: "inactive",
    department: "Поддержка",
    cost: 1100,
    currency: "USD",
    billingCycle: "month",
    nextPayment: "2026-07-01",
    users: ["e12"],
  },
];

export const employees: Employee[] = [
  {
    id: "e1",
    name: "Ivan Petrov",
    email: "ivan@corp.local",
    role: "Менеджер",
    department: "Разработка",
    subscriptions: ["s1", "s3"],
  },
  {
    id: "e2",
    name: "Anna Smirnova",
    email: "anna@corp.local",
    role: "Администратор",
    department: "Продукт",
    subscriptions: ["s1", "s2"],
  },
  {
    id: "e3",
    name: "Max Volkov",
    email: "max@corp.local",
    role: "Сотрудник",
    department: "Дизайн",
    subscriptions: ["s2"],
  },
  {
    id: "e4",
    name: "Olga Romanova",
    email: "olga@corp.local",
    role: "Сотрудник",
    department: "Операции",
    subscriptions: ["s4"],
  },
  {
    id: "e5",
    name: "Sergey Egorov",
    email: "sergey@corp.local",
    role: "Сотрудник",
    department: "Операции",
    subscriptions: ["s4"],
  },
  {
    id: "e6",
    name: "Daria Kozlova",
    email: "daria@corp.local",
    role: "Менеджер",
    department: "Операции",
    subscriptions: ["s4"],
  },
  {
    id: "e7",
    name: "Nikita Sokolov",
    email: "nikita@corp.local",
    role: "Сотрудник",
    department: "HR",
    subscriptions: ["s5"],
  },
  {
    id: "e8",
    name: "Elena Morozova",
    email: "elena@corp.local",
    role: "Администратор",
    department: "HR",
    subscriptions: ["s5"],
  },
  {
    id: "e9",
    name: "Kirill Novikov",
    email: "kirill@corp.local",
    role: "Лид DevOps",
    department: "Разработка",
    subscriptions: ["s6"],
  },
  {
    id: "e10",
    name: "Pavel Ivanov",
    email: "pavel@corp.local",
    role: "Менеджер",
    department: "Продажи",
    subscriptions: ["s7"],
  },
  {
    id: "e11",
    name: "Maria Denisova",
    email: "maria@corp.local",
    role: "Сотрудник",
    department: "Продажи",
    subscriptions: ["s7"],
  },
  {
    id: "e12",
    name: "Alexey Popov",
    email: "alexey@corp.local",
    role: "Лид поддержки",
    department: "Поддержка",
    subscriptions: ["s8"],
  },
];

export const reportsData: ReportData = {
  totalSpend: 28760,
  currency: "USD",
  byCategory: [
    { name: "DevOps", value: 5200 },
    { name: "Продуктивность", value: 3900 },
    { name: "Дизайн", value: 2100 },
    { name: "CRM", value: 3500 },
    { name: "Офис", value: 2300 },
    { name: "Коллаборация", value: 780 },
  ],
  byDepartment: [
    { name: "Разработка", value: 6100 },
    { name: "Продукт", value: 3600 },
    { name: "Операции", value: 3140 },
    { name: "Продажи", value: 3500 },
    { name: "HR", value: 780 },
  ],
  monthly: [
    { month: "Jan", value: 9800 },
    { month: "Feb", value: 10400 },
    { month: "Mar", value: 11100 },
    { month: "Apr", value: 12840 },
    { month: "May", value: 14550 },
    { month: "Jun", value: 16700 },
    { month: "Jul", value: 18200 },
    { month: "Aug", value: 20140 },
    { month: "Sep", value: 22300 },
    { month: "Oct", value: 24100 },
    { month: "Nov", value: 26620 },
    { month: "Dec", value: 28760 },
  ],
  unused: [
    { name: "Miro", department: "HR", seats: 8 },
    { name: "Confluence", department: "Engineering", seats: 14 },
    { name: "Calendly", department: "Sales", seats: 5 },
  ],
};

export const notifications: NotificationItem[] = [
  {
    id: "n1",
    title: "Figma Org истекает через 14 дней",
    kind: "renewal",
    at: "Сегодня",
  },
  {
    id: "n2",
    title: "Новый доступ к Notion назначен Ivan Petrov",
    kind: "assignment",
    at: "Вчера",
  },
  {
    id: "n3",
    title: "Google Workspace продлен на 12 месяцев",
    kind: "change",
    at: "2 дня назад",
  },
  {
    id: "n4",
    title: "GitLab Ultimate истекает через 30 дней",
    kind: "renewal",
    at: "2 дня назад",
  },
  {
    id: "n5",
    title: "Новый доступ к HubSpot назначен Pavel Ivanov",
    kind: "assignment",
    at: "3 дня назад",
  },
  {
    id: "n6",
    title: "Intercom деактивирован для отдела Support",
    kind: "change",
    at: "5 дней назад",
  },
];
